@host=https://localhost:7073

POST {{host}}/api/tasks
Content-Type: application/json

{
    "taskItemDetails": {
        "Name": "item1",
        "description": "Do work"
    },
    "startDate": "2023-02-15T05:00:00",
    "dueDate": "2023-02-15",
    "remindMe": true,
    "reminderMinutesBeforeDue": 15,
    "subItems": [
      "item2"
    ]
}

### end of request